import type { Quote } from "@/lib/types";

/**
 * Bundled quotes dataset — public-domain literature, science, speeches and
 * proverbs. Length class is computed from the actual character count so the
 * short/medium/long filters are correct by construction.
 */
const RAW: { text: string; source: string }[] = [
  { text: "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair.", source: "Charles Dickens, A Tale of Two Cities" },
  { text: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.", source: "Jane Austen, Pride and Prejudice" },
  { text: "Call me Ishmael. Some years ago, never mind how long precisely, having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world.", source: "Herman Melville, Moby-Dick" },
  { text: "I went to the woods because I wished to live deliberately, to front only the essential facts of life, and see if I could not learn what it had to teach, and not, when I came to die, discover that I had not lived.", source: "Henry David Thoreau, Walden" },
  { text: "The only thing we have to fear is fear itself.", source: "Franklin D. Roosevelt" },
  { text: "Ask not what your country can do for you; ask what you can do for your country.", source: "John F. Kennedy" },
  { text: "In the beginning God created the heaven and the earth. And the earth was without form, and void; and darkness was upon the face of the deep.", source: "Genesis 1:1-2" },
  { text: "To be, or not to be, that is the question: whether 'tis nobler in the mind to suffer the slings and arrows of outrageous fortune, or to take arms against a sea of troubles and by opposing end them.", source: "William Shakespeare, Hamlet" },
  { text: "All the world's a stage, and all the men and women merely players; they have their exits and their entrances, and one man in his time plays many parts.", source: "William Shakespeare, As You Like It" },
  { text: "The quick brown fox jumps over the lazy dog.", source: "Typing pangram" },
  { text: "Happy families are all alike; every unhappy family is unhappy in its own way.", source: "Leo Tolstoy, Anna Karenina" },
  { text: "It does not do to dwell on dreams and forget to live.", source: "J.K. Rowling, Harry Potter and the Philosopher's Stone" },
  { text: "There is nothing either good or bad, but thinking makes it so.", source: "William Shakespeare, Hamlet" },
  { text: "Not all those who wander are lost.", source: "J.R.R. Tolkien, The Fellowship of the Ring" },
  { text: "The unexamined life is not worth living.", source: "Socrates" },
  { text: "I have not failed. I've just found ten thousand ways that won't work.", source: "Thomas Edison" },
  { text: "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.", source: "Albert Einstein" },
  { text: "Somewhere, something incredible is waiting to be known.", source: "Carl Sagan" },
  { text: "The cosmos is within us. We are made of star-stuff. We are a way for the universe to know itself.", source: "Carl Sagan" },
  { text: "It is not the strongest of the species that survives, nor the most intelligent that survives. It is the one that is most adaptable to change.", source: "attributed to Charles Darwin" },
  { text: "There is grandeur in this view of life, with its several powers, having been originally breathed into a few forms or into one; and that, whilst this planet has gone cycling on according to the fixed law of gravity, from so simple a beginning endless forms most beautiful and most wonderful have been, and are being, evolved.", source: "Charles Darwin, On the Origin of Species" },
  { text: "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.", source: "Marie Curie" },
  { text: "If I have seen further it is by standing on the shoulders of giants.", source: "Isaac Newton" },
  { text: "The important thing is not to stop questioning. Curiosity has its own reason for existing.", source: "Albert Einstein" },
  { text: "Two roads diverged in a wood, and I took the one less traveled by, and that has made all the difference.", source: "Robert Frost, The Road Not Taken" },
  { text: "Hope is the thing with feathers that perches in the soul, and sings the tune without the words, and never stops at all.", source: "Emily Dickinson" },
  { text: "Do not go gentle into that good night. Rage, rage against the dying of the light.", source: "Dylan Thomas" },
  { text: "I took a deep breath and listened to the old brag of my heart. I am, I am, I am.", source: "Sylvia Plath, The Bell Jar" },
  { text: "We are all in the gutter, but some of us are looking at the stars.", source: "Oscar Wilde, Lady Windermere's Fan" },
  { text: "Be yourself; everyone else is already taken.", source: "attributed to Oscar Wilde" },
  { text: "It is never too late to be what you might have been.", source: "attributed to George Eliot" },
  { text: "Whatever our souls are made of, his and mine are the same.", source: "Emily Bronte, Wuthering Heights" },
  { text: "All we have to decide is what to do with the time that is given us. There are other forces at work in this world besides the will of evil.", source: "J.R.R. Tolkien, The Fellowship of the Ring" },
  { text: "It matters not how strait the gate, how charged with punishments the scroll, I am the master of my fate, I am the captain of my soul.", source: "William Ernest Henley, Invictus" },
  { text: "The man who does not read has no advantage over the man who cannot read.", source: "attributed to Mark Twain" },
  { text: "The secret of getting ahead is getting started.", source: "attributed to Mark Twain" },
  { text: "Courage is resistance to fear, mastery of fear, not absence of fear.", source: "Mark Twain" },
  { text: "It was a bright cold day in April, and the clocks were striking thirteen. Winston Smith, his chin nuzzled into his breast in an effort to escape the vile wind, slipped quickly through the glass doors of Victory Mansions, though not quickly enough to prevent a swirl of gritty dust from entering along with him.", source: "George Orwell, 1984" },
  { text: "War is peace. Freedom is slavery. Ignorance is strength.", source: "George Orwell, 1984" },
  { text: "All animals are equal, but some animals are more equal than others.", source: "George Orwell, Animal Farm" },
  { text: "In my younger and more vulnerable years my father gave me some advice that I've been turning over in my mind ever since. Whenever you feel like criticizing any one, he told me, just remember that all the people in this world haven't had the advantages that you've had.", source: "F. Scott Fitzgerald, The Great Gatsby" },
  { text: "So we beat on, boats against the current, borne back ceaselessly into the past.", source: "F. Scott Fitzgerald, The Great Gatsby" },
  { text: "Real courage is when you know you're licked before you begin, but you begin anyway and see it through no matter what.", source: "Harper Lee, To Kill a Mockingbird" },
  { text: "You never really understand a person until you consider things from his point of view, until you climb into his skin and walk around in it.", source: "Harper Lee, To Kill a Mockingbird" },
  { text: "It is our choices that show what we truly are, far more than our abilities.", source: "J.K. Rowling, Harry Potter and the Chamber of Secrets" },
  { text: "The truth is rarely pure and never simple.", source: "Oscar Wilde, The Importance of Being Earnest" },
  { text: "Simplicity is the ultimate sophistication.", source: "attributed to Leonardo da Vinci" },
  { text: "Well done is better than well said.", source: "Benjamin Franklin" },
  { text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", source: "attributed to Benjamin Franklin" },
  { text: "An investment in knowledge pays the best interest.", source: "Benjamin Franklin" },
  { text: "The journey of a thousand miles begins with a single step.", source: "Lao Tzu" },
  { text: "When you have eliminated the impossible, whatever remains, however improbable, must be the truth.", source: "Arthur Conan Doyle, The Sign of the Four" },
  { text: "It is a capital mistake to theorize before one has data. Insensibly one begins to twist facts to suit theories, instead of theories to suit facts.", source: "Arthur Conan Doyle, A Scandal in Bohemia" },
  { text: "Whether I shall turn out to be the hero of my own life, or whether that station will be held by anybody else, these pages must show. To begin my life with the beginning of my life, I record that I was born, as I have been informed and believe, on a Friday, at twelve o'clock at night.", source: "Charles Dickens, David Copperfield" },
  { text: "The world breaks everyone and afterward many are strong at the broken places.", source: "Ernest Hemingway, A Farewell to Arms" },
  { text: "There is no friend as loyal as a book.", source: "attributed to Ernest Hemingway" },
  { text: "Beware; for I am fearless, and therefore powerful.", source: "Mary Shelley, Frankenstein" },
  { text: "Nothing is so painful to the human mind as a great and sudden change.", source: "Mary Shelley, Frankenstein" },
  { text: "I am no bird; and no net ensnares me: I am a free human being with an independent will.", source: "Charlotte Bronte, Jane Eyre" },
  { text: "We must be willing to let go of the life we planned so as to have the life that is waiting for us.", source: "Joseph Campbell" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", source: "Marcus Aurelius, Meditations" },
  { text: "You have power over your mind, not outside events. Realize this, and you will find strength.", source: "Marcus Aurelius, Meditations" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", source: "Marcus Aurelius, Meditations" },
  { text: "We suffer more often in imagination than in reality.", source: "Seneca" },
  { text: "Luck is what happens when preparation meets opportunity.", source: "Seneca" },
  { text: "The whole future lies in uncertainty: live immediately.", source: "Seneca, On the Shortness of Life" },
  { text: "It is not that we have a short time to live, but that we waste a lot of it. Life is long enough, and a sufficiently generous amount has been given to us for the highest achievements if it were all well invested.", source: "Seneca, On the Shortness of Life" },
  { text: "Speed is not your enemy; inaccuracy is. Type each word as if it were the only one on the page, and the speed will arrive on its own schedule.", source: "Typing proverb" },
  { text: "The keyboard is learned by the hands, not by the eyes. Every glance downward teaches your fingers to forget.", source: "Typing proverb" },
  { text: "Practice does not make perfect. Only perfect practice makes perfect.", source: "Vince Lombardi" },
  { text: "How we spend our days is, of course, how we spend our lives. What we do with this hour, and that one, is what we are doing.", source: "Annie Dillard, The Writing Life" },
  { text: "Either write something worth reading or do something worth writing.", source: "attributed to Benjamin Franklin" },
  { text: "You miss one hundred percent of the shots you never take.", source: "Wayne Gretzky" },
  { text: "It always seems impossible until it is done.", source: "attributed to Nelson Mandela" },
  { text: "I am the wisest man alive, for I know one thing, and that is that I know nothing.", source: "attributed to Socrates" },
  { text: "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle.", source: "Steve Jobs" },
  { text: "Design is not just what it looks like and feels like. Design is how it works.", source: "Steve Jobs" },
  { text: "Any sufficiently advanced technology is indistinguishable from magic.", source: "Arthur C. Clarke" },
  { text: "The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.", source: "Isaac Asimov" },
  { text: "Programs must be written for people to read, and only incidentally for machines to execute.", source: "Harold Abelson, Structure and Interpretation of Computer Programs" },
  { text: "Premature optimization is the root of all evil.", source: "Donald Knuth" },
  { text: "There are only two hard things in computer science: cache invalidation and naming things.", source: "Phil Karlton" },
  { text: "Talk is cheap. Show me the code.", source: "Linus Torvalds" },
  { text: "First, solve the problem. Then, write the code.", source: "John Johnson" },
  { text: "Simplicity is prerequisite for reliability.", source: "Edsger Dijkstra" },
  { text: "The computer was born to solve problems that did not exist before.", source: "Bill Gates" },
  { text: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover.", source: "attributed to Mark Twain" },
  { text: "Far better it is to dare mighty things, to win glorious triumphs, even though checkered by failure, than to rank with those poor spirits who neither enjoy much nor suffer much, because they live in the gray twilight that knows not victory nor defeat.", source: "Theodore Roosevelt" },
  { text: "It is not the critic who counts; not the man who points out how the strong man stumbles, or where the doer of deeds could have done them better. The credit belongs to the man who is actually in the arena, whose face is marred by dust and sweat and blood; who strives valiantly; who errs, who comes short again and again.", source: "Theodore Roosevelt, Citizenship in a Republic" },
  { text: "Four score and seven years ago our fathers brought forth on this continent a new nation, conceived in liberty, and dedicated to the proposition that all men are created equal. Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived and so dedicated, can long endure.", source: "Abraham Lincoln, Gettysburg Address" },
  { text: "In the end, it's not the years in your life that count. It's the life in your years.", source: "attributed to Abraham Lincoln" },
  { text: "We choose to go to the Moon in this decade and do the other things, not because they are easy, but because they are hard; because that goal will serve to organize and measure the best of our energies and skills.", source: "John F. Kennedy, Rice University" },
  { text: "That's one small step for a man, one giant leap for mankind.", source: "Neil Armstrong" },
  { text: "I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character.", source: "Martin Luther King Jr." },
  { text: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.", source: "Martin Luther King Jr." },
  { text: "Injustice anywhere is a threat to justice everywhere.", source: "Martin Luther King Jr., Letter from Birmingham Jail" },
  { text: "The arc of the moral universe is long, but it bends toward justice.", source: "Martin Luther King Jr." },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", source: "attributed to Winston Churchill" },
  { text: "We shall fight on the beaches, we shall fight on the landing grounds, we shall fight in the fields and in the streets, we shall fight in the hills; we shall never surrender.", source: "Winston Churchill" },
  { text: "If you're going through hell, keep going.", source: "attributed to Winston Churchill" },
  { text: "A river cuts through rock, not because of its power, but because of its persistence.", source: "James N. Watkins" },
  { text: "Fall seven times, stand up eight.", source: "Japanese proverb" },
  { text: "The best time to plant a tree was twenty years ago. The second best time is now.", source: "Chinese proverb" },
  { text: "A smooth sea never made a skilled sailor.", source: "Proverb" },
  { text: "Slow is smooth, and smooth is fast.", source: "Military adage" },
  { text: "Vision without action is a daydream. Action without vision is a nightmare.", source: "Japanese proverb" },
  { text: "When the wind of change blows, some build walls, others build windmills.", source: "Chinese proverb" },
  { text: "He who asks a question is a fool for five minutes; he who does not ask a question remains a fool forever.", source: "Chinese proverb" },
  { text: "Everything should be made as simple as possible, but not simpler.", source: "attributed to Albert Einstein" },
  { text: "Whatever you are, be a good one.", source: "attributed to Abraham Lincoln" },
  { text: "There is nothing permanent except change.", source: "Heraclitus" },
  { text: "No man ever steps in the same river twice, for it is not the same river and he is not the same man.", source: "Heraclitus" },
  { text: "Quality is not an act, it is a habit.", source: "attributed to Aristotle" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", source: "Will Durant, on Aristotle" },
  { text: "Knowing yourself is the beginning of all wisdom.", source: "attributed to Aristotle" },
  { text: "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", source: "Dr. Seuss, I Can Read With My Eyes Shut!" },
  { text: "Why fit in when you were born to stand out?", source: "Dr. Seuss" },
  { text: "It is only with the heart that one can see rightly; what is essential is invisible to the eye.", source: "Antoine de Saint-Exupery, The Little Prince" },
  { text: "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.", source: "Antoine de Saint-Exupery" },
  { text: "A goal without a plan is just a wish.", source: "Antoine de Saint-Exupery" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", source: "Eleanor Roosevelt" },
  { text: "No one can make you feel inferior without your consent.", source: "Eleanor Roosevelt" },
  { text: "Do one thing every day that scares you.", source: "attributed to Eleanor Roosevelt" },
  { text: "In three words I can sum up everything I've learned about life: it goes on.", source: "Robert Frost" },
  { text: "The woods are lovely, dark and deep, but I have promises to keep, and miles to go before I sleep, and miles to go before I sleep.", source: "Robert Frost, Stopping by Woods on a Snowy Evening" },
];

export const QUOTES: Quote[] = RAW.map((q) => ({
  ...q,
  length:
    q.text.length < 150 ? "short" : q.text.length <= 300 ? "medium" : "long",
}));
